#!/bin/bash

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "jacobian_correction.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-2:2]

set ytics nomirror scale 0
set format y ''
set yrange[-2:2]

set zlabel ''
set zrange[-1.5:1.5]

unset cbtics
unset colorbox

# Teal to white to maroon palatte
set palette model HSV defined (0 180/360.0 1.0 0.49, 1 180/360.0 0.727 0.561, 2 180/360.0 0.503 0.639, 3 180/360.0 0.328 0.729, 4 180/360.0 0.230 0.784, 5 180/360.0 0.145 0.863, 6 180/360.0 0.072 0.922, 7 180/360.0 0.033 0.961, 8 180/360.0 0.008 0.992, 9 0 0 1, 10 0/360.0 0.008 0.992, 11 0/360.0 0.033 0.961, 12 0/360.0 0.072 0.922, 13 0/360.0 0.145 0.863, 14 0/360.0 0.230 0.784, 15 0/360.0 0.328 0.729, 16 0/360.0 0.503 0.639, 17 0/360.0 0.727 0.561, 18 0/360.0 1.0 0.49)

set samples 200
set isosamples 200

eta = 1.5
alpha = 10
beta = 2.5
gamma = 10

f1(x, y) = x * ( eta - alpha / (beta * (x**2 + y**2) + gamma) )
f2(x, y) = y * ( eta - alpha / (beta * (x**2 + y**2) + gamma) )

df1dx(x, y) =   ( eta - alpha / (beta * (x**2 + y**2) + gamma) ) \
              + 2 * alpha * beta * x**2 / (beta * (x**2 + y**2) + gamma)**2
df2dy(x, y) =   ( eta - alpha / (beta * (x**2 + y**2) + gamma) ) \
              + 2 * alpha * beta * y**2 / (beta * (x**2 + y**2) + gamma)**2
df1dy(x, y) = 2 * alpha * beta * x * y / (beta * (x**2 + y**2) + gamma)**2
df2dx(x, y) = 2 * alpha * beta * x * y / (beta * (x**2 + y**2) + gamma)**2

detJ(x, y) = abs(df1dx(x, y) * df2dy(x, y) - df1dy(x, y) * df2dx(x, y))

splot log(1 / detJ(x, y)) notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 0.5, 5
set output "color_bar.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-1.5:1.5]

set ytics nomirror scale 0
set format y ''
set yrange[-1.5:1.5]

set zlabel ''
set zrange[-1.5:1.5]

unset cbtics
unset colorbox

# Teal to white to maroon palatte
set palette model HSV defined (0 180/360.0 1.0 0.49, 1 180/360.0 0.727 0.561, 2 180/360.0 0.503 0.639, 3 180/360.0 0.328 0.729, 4 180/360.0 0.230 0.784, 5 180/360.0 0.145 0.863, 6 180/360.0 0.072 0.922, 7 180/360.0 0.033 0.961, 8 180/360.0 0.008 0.992, 9 0 0 1, 10 0/360.0 0.008 0.992, 11 0/360.0 0.033 0.961, 12 0/360.0 0.072 0.922, 13 0/360.0 0.145 0.863, 14 0/360.0 0.230 0.784, 15 0/360.0 0.328 0.729, 16 0/360.0 0.503 0.639, 17 0/360.0 0.727 0.561, 18 0/360.0 1.0 0.49)

set samples 200
set isosamples 200

splot y notitle

END
